### ISSUE TITLE
Simplify Access to Validation Status and Messages

### ISSUE THREAD

**Issue by ghost** [bsh-devsolutions/libs.validation.ts#2]
#### Summary:
The current method of accessing validation statuses and messages involves deep property access (e.g., `validator.items.<item>.<message|valid|validate>`). To enhance usability and improve code readability, a simpler and more intuitive way to access validation results should be provided.

#### Use Case:
In many scenarios, developers need to quickly and easily check the validation status of various fields or elements. The existing method, which requires navigating through multiple properties (`validator.items.<item>.<message|valid|validate>`), can be cumbersome, especially when dealing with complex forms or data structures. 

A simplified API for accessing validation status and messages would streamline development, reduce errors, and improve overall developer experience.

#### Expected Behavior:
1. **Simplified Access**:
   - Introduce a new method or property that provides direct access to validation statuses and messages.
   - Example: Instead of using `validator.items.username.valid`, allow access through a simpler syntax like `validator.getStatus('username').valid`.

2. **Flexible Retrieval**:
   - Allow retrieval of validation results for multiple fields at once.
   - Example: `validator.getStatuses(['username', 'email'])` could return an object with validation statuses for both fields.

3. **Consistent and Intuitive API**:
   - Ensure that the new access pattern is consistent with the existing API and easy to understand.

4. **Backward Compatibility**:
   - Maintain backward compatibility to ensure that existing codebases are not broken by this change.

#### Possible Implementation:
- Introduce a new method, such as `getStatus(fieldName)` or `getStatuses(fieldNamesArray)`, that returns the validation status and message in a simplified format.
- Example:
  ```javascript
  const usernameStatus = validator.getStatus('username');
  console.log(usernameStatus.valid); // true or false
  console.log(usernameStatus.message); // Error message if any

  const statuses = validator.getStatuses(['username', 'email']);
  console.log(statuses); 
  // { username: { valid: true, message: '' }, email: { valid: false, message: 'Invalid email' } }

**Comment by hamza-bousalih** [comment]
three functions are added to `Validator` to simplify the access to items status:
```ts
validator.validateItem('filed-name') // replacing : validator.items?.email?.validate()
validator.itemMessage('filed-name') // replacing : validator.items?.email?.message
validator.isItemValid('filed-name') // replacing : validator.items?.email?.valid
```
